iptables_tcp_open_ports: []
iptables_udp_open_ports: [22420, 22422, 22425]

internal_network_subnet: "192.168.22.0/24"
internal_network_border_address: "192.168.22.254"

nat_interface: "eth0"

# For traffic forwarding
traffic_forwarding: {}
